### ISSUE TITLE
Using Multi-scale Deformable Attention

### ISSUE THREAD

**Issue by Sairam13001** [qianyuzqy/TransVOD_Lite#10]
Hi @qianyuzqy,

I am running your code on my custom dataset which has very small sized objects. I have been trying to pass multi-scale features coming from the Swin_b backbone to Deformable DETR. I made a few changes accordingly.  
 
If I pass a batch of images of shape (bs, 640, 640, 3) to swin, I get (bs, 256, 80, 80), (bs, 256, 40, 40) and (bs, 256, 20, 20) shaped features from the last three layers of swin.  Instead of upasmpling and aggregating these features to a single feature of shape (bs, 256, 80, 80), I am passing them as it is to Deformable DETR to leverage the multi-scale deformable attentions. While preparing input to Deformable DETR, we add features along the channel dimensions right, so, the features now become (bs,8400, 256) where 8400 = 80x80 + 40x40 + 20x20. 

Everything is working fine until Encoder. In decoder, I am getting this error: 

Traceback (most recent call last):
  File "main.py", line 348, in <module>
    main(args)
  File "main.py", line 305, in main
    train_stats = train_one_epoch(
  File "/workspace/engine_single.py", line 82, in train_one_epoch
    outputs = model(samples, targets)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/models/deformable_detr_single.py", line 388, in forward
    hs, init_reference, inter_references, enc_outputs_class, enc_outputs_coord_unact = self.transformer(srcs, masks, pos, query_embeds)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/models/deformable_transformer_single.py", line 211, in forward
    hs, inter_references = self.decoder(tgt, reference_points, memory,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/models/deformable_transformer_single.py", line 398, in forward
    output = layer(output, query_pos, reference_points_input, src, src_spatial_shapes, src_level_start_index, src_padding_mask)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/models/deformable_transformer_single.py", line 370, in forward
    tgt = self.forward_ffn(tgt)
  File "/workspace/models/deformable_transformer_single.py", line 344, in forward_ffn
    tgt2 = self.linear2(self.dropout3(self.activation(self.linear1(tgt))))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1616554793803/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:155, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.

Could you kindly let me know why this problem occurs?

**Comment by qianyuzqy** [comment]
Hi, @Sairam13001 ,

I am very sorry that I have not met this error before. The motivation for upsampling and aggregating these features to a single scale feature is that we want to use each frame of the video clip as a 'scale' in the multi-scale deformable attention. We have not passed multi-scale features coming from the Swin_b backbone to Deformable DETR yet. Maybe you can have a try.
